#include "schoolscannerdefinities.h"

typedef ColumnDefinition	CD;

const ColumnDefinitions SchoolScannerDefinities::_columnDefs =
{

	new CD("Tijdstempel",																														"timestamp",															ColumnType::DateTime	),
	new CD("Wat is de datum?",																													"datum",																ColumnType::DateTime	),
	new CD("Ben je een jongen of meisje?",																										"gender",																ColumnType::Label   	),
	new CD("Wat is jouw culturele achtergrond?",																								"cultuur",																ColumnType::Text    	),
	new CD("Op welke school zit je?",																											"school",																ColumnType::Label   	),
	new CD("Op welke school/locatie heb je les?",																								"locatie",																ColumnType::Label   	),
	new CD("Welke opleiding volg je?",																											"opleiding",															ColumnType::Text    	),
	new CD("Onder welke sector valt jouw opleiding?",																							"sector",																ColumnType::Text    	),
	new CD("In welk jaar zit je?",																												"jaar",																	ColumnType::Label   	),
	new CD("In welke klas zit je?",																												"klas",																	ColumnType::Text    	),
	new CD("Welk opleidingstraject volg je?",																									"opleidingstraject",													ColumnType::Label    	),
	new CD("Welk niveau volg je?",																												"niveau",																ColumnType::Label   	),
	new CD("Ik voel me veilig  [Ik voel me veilig op school]",																					"veiligSchool",															ColumnType::NumInt  	),
	new CD("Ik voel me veilig  [Ik voel me veilig in de klas]",																					"veiligKlas",															ColumnType::NumInt     	),
	new CD("Ik voel me onveilig in/op/bij",																										"onveiligHier",															ColumnType::Labels    	),
	new CD(" [Ik ben wel eens bang op school]",																									"bangOpSchool",															ColumnType::Label		),
	new CD(" [Ik ga graag naar school]",																										"graagNaarSchool",														ColumnType::Label		),
	new CD("2. In de klas [In onze klas kun je jezelf zijn]",																					"klasJezelf",															ColumnType::Label		),
	new CD("2. In de klas [De sfeer in de klas is goed]",																						"klasSfeerGoed",														ColumnType::Label		),
	new CD("2. In de klas [Er wordt in mijn klas gemopperd over school]",																		"klasSchoolGemopper",													ColumnType::Label		),
	new CD("2. In de klas [Ik kan goed opschieten met mijn klasgenoten]",																		"klasOpschietenMet",													ColumnType::Label		),
	new CD("2. In de klas [In de klas kunnen we goed met elkaar samenwerken]",																	"klasGoedSamenWerken",													ColumnType::Label		),
	new CD("2. In de klas [In de klas ga ik het liefst om met studenten die dezelfde afkomst hebben als ik]",									"klasAfkomstKlit",														ColumnType::Label		),
	new CD("2. In de klas [In de klas hoor ik dat studenten onaardig over elkaar spreken]",														"klasOnaardigGepraat",													ColumnType::Label		),
	new CD("2. In de klas [In de klas wordt veel ruzie gemaakt]",																				"klasVeelRuzie",														ColumnType::Label		),
	new CD("2. In de klas [Als iemand vervelend tegen je doet, kun je er wat van zeggen]",														"klasKunJeZeggenVervelend",												ColumnType::Label		),
	new CD("2. In de klas [Als ik homo of lesbisch zou zijn, dan mogen klasgenoten dat weten]",													"klasDurfUitDeKast",													ColumnType::Label		),
	new CD("2. In de klas [In de klas worden kwetsende opmerkingen gemaakt over mijn identiteit]",												"klasKwetstMetMijnIdentiteit",											ColumnType::Label		),
	new CD("2. In de klas [Mijn klasgenoten weten hoe het met mij gaat]",																		"klasWeetHoeHetMetMijGaat",												ColumnType::Label		),
	new CD("Sommige studenten maken vervelende dingen mee in de klas. Hoe komt dit?",															"waaromVervelendeDingenInDeKlas",										ColumnType::Labels		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... [...worden buitengesloten]",		                            		"studentenBuitenGesloten",												ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... [...worden uitgescholden]",				                                "studentenUitgescholden",												ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... [...met opzet de les verstoren]",			                        	"studentenExpresLesVerstoren",											ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... [...met opzet spullen vernielen, verstoppen of kwijtmaken]",			"studentenSpullenSlopenJatten",											ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... [...worden gepest]",				                                    "studentenGepest",														ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... […worden gepest via internet, smartphone, social media]",				"studentenDigitaalGepest",												ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... […worden gediscrimineerd (ongelijk behandeld) door medeleerlingen]",	"studentenGediscrimineerdDoorLeerlingen",								ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... […worden gediscrimineerd (ongelijk behandeld) door docenten]",			"studentenGediscrimineerdDoorLeraren",									ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... […worden bedreigd of geïntimideerd]",									"studentenBedreigdGeintimideerd",										ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... […worden geduwd, geschopt of geslagen]",								"studentenGeduwdGeschoptGeslagen",										ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... […met elkaar vechten]",												 	"studentenVechten",														ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... […seksueel getinte opmerkingen maken]",								    "studentenSeksueelGetinteOpmerkingenMaken",								ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... […seksuele afbeeldingen verspreiden]",									"studentenSeksueleAfbeeldingenVerspreiden",								ColumnType::Label		),
	new CD("Bij mij in de klas/op school zie ik dat andere studenten... [...zich niet veilig voelen in de klas]",								"studentenOnveiligVoelenInKlas",										ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...buitengesloten]",																				"ikBuitengesloten",														ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...uitgescholden]",																				"ikUitgescholden",														ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...expres gestoord]",																				"ikExpresGestoord",														ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...gepest]",																						"ikGepest",																ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...gepest via internet, smartphone, social media]",												"ikDigitaalGepest",														ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...gediscrimineerd (ongelijk behandeld) door medestudent]",										"ikGediscrimineerdDoorLeerlingen",										ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...gediscrimineerd (ongelijk behandeld) door docenten]",											"ikGediscrimineerdDoorLeraren",											ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...bedreigd of geïntimideerd]",																	"ikBedreigdGeintimideerd",												ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...geduwd, geschopt of geslagen]",																"ikGeduwdGeschoptGeslagen",												ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...uitgedaagd om te vechten]",																	"ikUitgedaagdOmTeVechten",												ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...aangesproken met seksueel getinte opmerkingen]",												"ikAangesprokenMetSeksueelGetinteOpmerkingen",							ColumnType::Label		),
	new CD("In de klas/op school word ik...  [...aangesproken op vervelend gedrag]",															"ikAangesprokenOpVervelendGedrag",										ColumnType::Label		),
	new CD("In de klas/op school worden mijn...  [...spullen met opzet vernield, verstopt of kwijtgemaakt]",									"mijnSpullenGeslooptGejat",												ColumnType::Label		),
	new CD("In de klas/op school worden mijn...  [...privéfoto’s verspreid]",																	"mijnPriveFotosVerspreid",												ColumnType::Label		),
	new CD(" [In de klas voel ik me onveilig]",																									"klasVoeltOnveilig",													ColumnType::Label		),
	new CD(" [Op school voel ik me onveilig]",																									"schoolVoeltOnveilig",													ColumnType::Label		),
	new CD("4. Op school [Op onze school kun je jezelf zijn]",																					"schoolJezelfZijn",														ColumnType::Label		),
	new CD("4. Op school [De sfeer op school is goed]",																							"schoolSfeerIsGoed",													ColumnType::Label		),
	new CD("4. Op school [Ik raad mijn school aan anderen aan]",																				"schoolRaadIkAan",														ColumnType::Label		),
	new CD("4. Op school [Op school worden studenten gediscrimineerd (ongelijk behandeld)]",													"schoolStudentenGediscrimineerd",										ColumnType::Label		),
	new CD("4. Op school [Studenten van verschillende afkomsten voelen zich thuis bij ons op school]",											"schoolDiversVoeltThuis",												ColumnType::Label		),
	new CD("4. Op school [Studenten kunnen op school goed met elkaar opschieten]",																"schoolGoedOpschietenElkaar",											ColumnType::Label		),
	new CD("4. Op school [Op school ga ik het liefst om met studenten die dezelfde afkomst hebben als ik]",										"schoolLiefstMetGelijkeAfkomstOm",										ColumnType::Label		),
	new CD("4. Op school [Op school worden anderen voorgetrokken op basis van afkomst, cultuur of geloof]",										"schoolAnderenVoorgetrokkenAfkomstCultuurGeloof",						ColumnType::Label		),
	new CD("4. Op school [Actuele gebeurtenissen in de wereld die voor mij van belang zijn komen aan bod op school]",							"schoolActueleGebeurtenissenMijAangaanBehandeldOpSchool",				ColumnType::Label		),
	new CD("4. Op school [In de pauze zie ik vaak studenten ongewild alleen zitten]",															"schoolStudentenZittenOngewildAlleen",									ColumnType::Label		),
	new CD("5. Zo werken wij op school      [Op school zijn duidelijke regels/afspraken over hoe we met elkaar omgaan]",						"werkenSchoolDuidelijkeRegelsOmgang",									ColumnType::Label		),
	new CD("5. Zo werken wij op school      [De regels op school zijn voor iedereen gelijk]",													"werkenSchoolRegelsIedereenGelijk",										ColumnType::Label		),
	new CD("5. Zo werken wij op school      [Studenten die zich niet aan de regels houden, worden daarop aangesproken]",						"werkenSchoolStudentenDieRegelsBrekenAangesproken",						ColumnType::Label		),
	new CD("5. Zo werken wij op school      [Docenten die zich niet aan de regels houden, worden daarop aangesproken]",							"werkenSchoolDocentenDieRegelsBrekenAangesproken",						ColumnType::Label		),
	new CD("5. Zo werken wij op school      [De regels zijn bij elke docent hetzelfde]",														"werkenSchoolRegelsIedereDocentGelijk",									ColumnType::Label		),
	new CD("5. Zo werken wij op school      [Ik weet bij wie ik op school terecht kan met mijn problemen]",										"werkenSchoolOmbudBekend",												ColumnType::Label		),
	new CD("5. Zo werken wij op school      [De mening van studenten telt mee op onze school]",													"werkenSchoolMeningStudentenTelt",										ColumnType::Label		),
	new CD("5. Zo werken wij op school      [Studenten hebben respect voor docenten]",															"werkenSchoolStudentenHebbenRespectVoorDocenten",						ColumnType::Label		),
	new CD("5. Zo werken wij op school      [Docenten hebben respect voor studenten]",															"werkenSchoolDocentenHebbenRespectVoorStudenten",						ColumnType::Label		),
	new CD("5. Zo werken wij op school      [Docenten geven op school het goede voorbeeld]",													"werkenSchoolDocentenGevenGoedeVoorbeeld",								ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... ga ik helpen]",														"vervelendDanGaIkHelpen",												ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... kijk ik weg]",															"vervelendDanKijkIkWeg",												ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... loop ik weg]",															"vervelendDanLoopIkWeg",												ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... doe ik mee]",															"vervelendDanDoeIkMee",													ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... zeg ik er wat van]",													"vervelendDanZegIkErWatVan",											ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... waarschuw ik een docent, mentor of conciërge]",						"vervelendDanWaarschuwIkSchoolMedewerker",								ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... laat ik hem/haar weten dat ik meeleef]",								"vervelendDanLaatIkMedelevenWeten",										ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... zie ik dat een andere student ingrijpt]",								"vervelendDanZieIkDatAndereStudentIngrijpt",							ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... zie ik dat een docent ingrijpt]",										"vervelendDanZieIkDatDocentIngrijpt",									ColumnType::Label		),
	new CD("Als iemand vervelend doet tegen een klasgenoot dan .... [... zie ik dat de afdelingsleider ingrijpt]",								"vervelendDanZieIkDatAfdelingsleiderIngrijpt",							ColumnType::Label		),
	new CD("Heb je de afgelopen week vervelende situaties (als pesten, buitensluiten etc.) gezien?",											"afgelopenWeekVervelendeSituatiesGezien",								ColumnType::Label		),
	new CD(" [Als ik een vervelende situatie zie, dan vind ik dat ik iets moet doen]",															"alsIkVervelendeSituatieZieDanVindIkDatIkWatMoetDoen",					ColumnType::Label		),
	new CD(" [Als ik een vervelende situatie zie, dat weet ik wat ik kan doen]",																"alsIkVervelendeSituatieZieDanWeetIkWatIkKanDoen",						ColumnType::Label		),
	new CD(" [Als een student wordt buitengesloten, dan is dat zijn/haar eigen keuze]",															"alsEenStudentWordtBuitengeslotenDanIsDatEigenKeuze",					ColumnType::Label		),
	new CD(" [Als een student wordt buitengesloten, dan is dat zijn/haar eigen schuld]",														"alsEenStudentWordtBuitengeslotenDanIsDatEigenSchuld",					ColumnType::Label		),
	new CD(" [Ik voel me verantwoordelijk om buitensluiten tegen te gaan]",																		"voelMeVerantwoordelijkOmBuitensluitenTegenTeGaan",						ColumnType::Label		),
	new CD(" [Ik voel me verantwoordelijk om in te grijpen als iemand wordt gediscrimineerd]",													"voelMeVerantwoordelijkOmInTeGrijpenAlsIemandWordtGediscrimineerd",		ColumnType::Label		),
	new CD(" [Ik voel me verantwoordelijk om in te grijpen als iemand wordt gepest]",															"voelMeVerantwoordelijkOmInTeGrijpenAlsIemandWordtGepest",				ColumnType::Label		),
	new CD(" [Ik stuur (weleens) privéfoto’s van andere studenten door]",																		"ikStuurWelEensPrivefotosAnderenDoor",									ColumnType::Label		),
	new CD("7. Docenten & mentoren [Ik heb goed contact met mijn mentor]",																		"mentorIkHebGoedContact",												ColumnType::Label		),
	new CD("7. Docenten & mentoren [Ik heb goed contact met mijn docenten]",																	"docentIkHebGoedContact",												ColumnType::Label		),
	new CD("7. Docenten & mentoren [Docenten kunnen goed orde houden in de klas]",																"docentenKunnenGoedOrdeHouden",											ColumnType::Label		),
	new CD("7. Docenten & mentoren [Ik krijg complimenten van docenten]",																		"docentenGevenMijComplimenten",											ColumnType::Label		),
	new CD("7. Docenten & mentoren [Docenten hebben een lage verwachting van mij]",																"docentenHebbenLageVerwachtingVanMij",									ColumnType::Label		),
	new CD("7. Docenten & mentoren [Docenten letten op het taalgebruik van de leerlingen]",														"docentenLettenOpTaalgebruikStudenten",									ColumnType::Label		),
	new CD("7. Docenten & mentoren [Docenten letten op hun eigen taalgebruik]",																	"docentenlettenOpEigenTaalgebruik",										ColumnType::Label		),
	new CD("7. Docenten & mentoren [Positief gedrag van studenten wordt door docenten beloond]",												"docentenBelonenPositiefGedrag",										ColumnType::Label		),
	new CD("7. Docenten & mentoren [Docenten grijpen in wanneer dat nodig is]",																	"docentenGrijpenInWanneerDatNodigIs",									ColumnType::Label		),
	new CD("7. Docenten & mentoren [Onze mentor weet wat er speelt in de klas]",																"mentorenWetenWatErInDeKlasSpeelt",										ColumnType::Label		),
	new CD("7. Docenten & mentoren [Onze mentor bespreekt wat er speelt in de klas]",															"mentorenBespreektWatErInDeKlasSpeelt",									ColumnType::Label		),
	new CD("7. Docenten & mentoren [Actuele gebeurtenissen in de samenleving worden in de klas besproken]",										"actueleGebeurtenissenSamenlevingWordenInKlasBesproken",				ColumnType::Label		),
	new CD("8. Waaraan vind jij dat jouw school meer moet doen? (max 3 antwoorden mogelijk)",													"waarMoetSchoolMeerAanDoen",											ColumnType::Text		)
};

const QString SchoolScannerDefinities::_tableName = "SchoolScanner";

const ColumnDefinitions & SchoolScannerDefinities::columnDefs()
{
	return _columnDefs;
}
